### ISSUE TITLE
Ruta del archivo en Dropbox

### ISSUE THREAD

**Issue by alu0100767421** [ULL-ESIT-SYTW-1617/passport-y-localstrategy-josue-nayra#2]
Hola chicos, les quería hacer un pregunta. La aplicación funciona pero a la hora de registrarme da error, creo que el problema es que no se cual es la ruta del Dropbox que hay que poner, por lo tanto como sería esta ruta?

**Comment by JosueTC94** [comment]
Teniamos unos fallos y creo que lo hemos arreglado ya por si quieres volver a intentarlo.
De todos modos, para poner la ruta de la base de datos de Dropbox tienes que darle a "compartir" en el fichero que tienes en Dropbox como base de datos y luego a "copiar enlace". Hemos actualizado el README.md informando un poco más sobre esto que nos comentas. Si quieres échale un vistazo y si sigues con fallos nos comentas.

@alu0100406122 

Gracias!!
Saludos.

**Comment by alu0100767421** [comment]
Muchas gracias, todo perfect
